/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OpenclawRouteImport } from './routes/openclaw'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ApiWorkoutSessionsRouteImport } from './routes/api/workout/sessions'
import { Route as ApiWorkoutProfileRouteImport } from './routes/api/workout/profile'
import { Route as ApiWorkoutExercisesRouteImport } from './routes/api/workout/exercises'
import { Route as ApiWorkoutDashboardRouteImport } from './routes/api/workout/dashboard'
import { Route as ApiWorkoutBodyMetricsRouteImport } from './routes/api/workout/body-metrics'
import { Route as ApiWorkoutAuditRouteImport } from './routes/api/workout/audit'
import { Route as ApiWorkoutAnalyticsRouteImport } from './routes/api/workout/analytics'
import { Route as ApiTournamentStartRouteImport } from './routes/api/tournament/start'
import { Route as ApiTournamentRoundsRouteImport } from './routes/api/tournament/rounds'
import { Route as ApiTournamentLiveRouteImport } from './routes/api/tournament/live'
import { Route as ApiTournamentLeaderboardRouteImport } from './routes/api/tournament/leaderboard'
import { Route as ApiOpenclawHealthRouteImport } from './routes/api/openclaw/health'
import { Route as ApiOpenclawAgentsRouteImport } from './routes/api/openclaw/agents'
import { Route as ApiMcpSearchBrainRouteImport } from './routes/api/mcp/search-brain'
import { Route as ApiHonestfitMissionSummaryRouteImport } from './routes/api/honestfit/mission-summary'
import { Route as ApiWorkoutSessionsIdRouteImport } from './routes/api/workout/sessions.$id'
import { Route as ApiWorkoutPlanTodayRouteImport } from './routes/api/workout/plan.today'
import { Route as ApiWorkoutPlanNextRouteImport } from './routes/api/workout/plan.next'
import { Route as ApiWorkoutPlanGenerateRouteImport } from './routes/api/workout/plan.generate'
import { Route as ApiWorkoutChatHelpRouteImport } from './routes/api/workout/chat.help'
import { Route as ApiWorkoutChatCommandRouteImport } from './routes/api/workout/chat.command'
import { Route as ApiOpenclawAgentsIdRouteImport } from './routes/api/openclaw/agents.$id'
import { Route as ApiIngestTradingBracketRouteImport } from './routes/api/ingest/trading.bracket'
import { Route as ApiIngestThoughtsRecentRouteImport } from './routes/api/ingest/thoughts.recent'
import { Route as ApiIngestThoughtsActivityRouteImport } from './routes/api/ingest/thoughts.activity'
import { Route as ApiWorkoutSessionsIdStartRouteImport } from './routes/api/workout/sessions.$id.start'
import { Route as ApiWorkoutSessionsIdSkipRouteImport } from './routes/api/workout/sessions.$id.skip'
import { Route as ApiWorkoutSessionsIdCompleteRouteImport } from './routes/api/workout/sessions.$id.complete'
import { Route as ApiWorkoutExercisePerformancesIdSetsRouteImport } from './routes/api/workout/exercise-performances.$id.sets'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenclawRoute = OpenclawRouteImport.update({
  id: '/openclaw',
  path: '/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const ApiWorkoutSessionsRoute = ApiWorkoutSessionsRouteImport.update({
  id: '/api/workout/sessions',
  path: '/api/workout/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutProfileRoute = ApiWorkoutProfileRouteImport.update({
  id: '/api/workout/profile',
  path: '/api/workout/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutExercisesRoute = ApiWorkoutExercisesRouteImport.update({
  id: '/api/workout/exercises',
  path: '/api/workout/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutDashboardRoute = ApiWorkoutDashboardRouteImport.update({
  id: '/api/workout/dashboard',
  path: '/api/workout/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutBodyMetricsRoute = ApiWorkoutBodyMetricsRouteImport.update({
  id: '/api/workout/body-metrics',
  path: '/api/workout/body-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutAuditRoute = ApiWorkoutAuditRouteImport.update({
  id: '/api/workout/audit',
  path: '/api/workout/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutAnalyticsRoute = ApiWorkoutAnalyticsRouteImport.update({
  id: '/api/workout/analytics',
  path: '/api/workout/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentStartRoute = ApiTournamentStartRouteImport.update({
  id: '/api/tournament/start',
  path: '/api/tournament/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentRoundsRoute = ApiTournamentRoundsRouteImport.update({
  id: '/api/tournament/rounds',
  path: '/api/tournament/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentLiveRoute = ApiTournamentLiveRouteImport.update({
  id: '/api/tournament/live',
  path: '/api/tournament/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentLeaderboardRoute =
  ApiTournamentLeaderboardRouteImport.update({
    id: '/api/tournament/leaderboard',
    path: '/api/tournament/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenclawHealthRoute = ApiOpenclawHealthRouteImport.update({
  id: '/api/openclaw/health',
  path: '/api/openclaw/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenclawAgentsRoute = ApiOpenclawAgentsRouteImport.update({
  id: '/api/openclaw/agents',
  path: '/api/openclaw/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpSearchBrainRoute = ApiMcpSearchBrainRouteImport.update({
  id: '/api/mcp/search-brain',
  path: '/api/mcp/search-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHonestfitMissionSummaryRoute =
  ApiHonestfitMissionSummaryRouteImport.update({
    id: '/api/honestfit/mission-summary',
    path: '/api/honestfit/mission-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkoutSessionsIdRoute = ApiWorkoutSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiWorkoutSessionsRoute,
} as any)
const ApiWorkoutPlanTodayRoute = ApiWorkoutPlanTodayRouteImport.update({
  id: '/api/workout/plan/today',
  path: '/api/workout/plan/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutPlanNextRoute = ApiWorkoutPlanNextRouteImport.update({
  id: '/api/workout/plan/next',
  path: '/api/workout/plan/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutPlanGenerateRoute = ApiWorkoutPlanGenerateRouteImport.update({
  id: '/api/workout/plan/generate',
  path: '/api/workout/plan/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutChatHelpRoute = ApiWorkoutChatHelpRouteImport.update({
  id: '/api/workout/chat/help',
  path: '/api/workout/chat/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkoutChatCommandRoute = ApiWorkoutChatCommandRouteImport.update({
  id: '/api/workout/chat/command',
  path: '/api/workout/chat/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenclawAgentsIdRoute = ApiOpenclawAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOpenclawAgentsRoute,
} as any)
const ApiIngestTradingBracketRoute = ApiIngestTradingBracketRouteImport.update({
  id: '/api/ingest/trading/bracket',
  path: '/api/ingest/trading/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestThoughtsRecentRoute = ApiIngestThoughtsRecentRouteImport.update({
  id: '/api/ingest/thoughts/recent',
  path: '/api/ingest/thoughts/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestThoughtsActivityRoute =
  ApiIngestThoughtsActivityRouteImport.update({
    id: '/api/ingest/thoughts/activity',
    path: '/api/ingest/thoughts/activity',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkoutSessionsIdStartRoute =
  ApiWorkoutSessionsIdStartRouteImport.update({
    id: '/start',
    path: '/start',
    getParentRoute: () => ApiWorkoutSessionsIdRoute,
  } as any)
const ApiWorkoutSessionsIdSkipRoute =
  ApiWorkoutSessionsIdSkipRouteImport.update({
    id: '/skip',
    path: '/skip',
    getParentRoute: () => ApiWorkoutSessionsIdRoute,
  } as any)
const ApiWorkoutSessionsIdCompleteRoute =
  ApiWorkoutSessionsIdCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiWorkoutSessionsIdRoute,
  } as any)
const ApiWorkoutExercisePerformancesIdSetsRoute =
  ApiWorkoutExercisePerformancesIdSetsRouteImport.update({
    id: '/api/workout/exercise-performances/$id/sets',
    path: '/api/workout/exercise-performances/$id/sets',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/openclaw': typeof OpenclawRoute
  '/search': typeof SearchRoute
  '/thoughts': typeof ThoughtsRoute
  '/trading': typeof TradingRoute
  '/workout': typeof WorkoutRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/honestfit/mission-summary': typeof ApiHonestfitMissionSummaryRoute
  '/api/mcp/search-brain': typeof ApiMcpSearchBrainRoute
  '/api/openclaw/agents': typeof ApiOpenclawAgentsRouteWithChildren
  '/api/openclaw/health': typeof ApiOpenclawHealthRoute
  '/api/tournament/leaderboard': typeof ApiTournamentLeaderboardRoute
  '/api/tournament/live': typeof ApiTournamentLiveRoute
  '/api/tournament/rounds': typeof ApiTournamentRoundsRoute
  '/api/tournament/start': typeof ApiTournamentStartRoute
  '/api/workout/analytics': typeof ApiWorkoutAnalyticsRoute
  '/api/workout/audit': typeof ApiWorkoutAuditRoute
  '/api/workout/body-metrics': typeof ApiWorkoutBodyMetricsRoute
  '/api/workout/dashboard': typeof ApiWorkoutDashboardRoute
  '/api/workout/exercises': typeof ApiWorkoutExercisesRoute
  '/api/workout/profile': typeof ApiWorkoutProfileRoute
  '/api/workout/sessions': typeof ApiWorkoutSessionsRouteWithChildren
  '/api/ingest/thoughts/activity': typeof ApiIngestThoughtsActivityRoute
  '/api/ingest/thoughts/recent': typeof ApiIngestThoughtsRecentRoute
  '/api/ingest/trading/bracket': typeof ApiIngestTradingBracketRoute
  '/api/openclaw/agents/$id': typeof ApiOpenclawAgentsIdRoute
  '/api/workout/chat/command': typeof ApiWorkoutChatCommandRoute
  '/api/workout/chat/help': typeof ApiWorkoutChatHelpRoute
  '/api/workout/plan/generate': typeof ApiWorkoutPlanGenerateRoute
  '/api/workout/plan/next': typeof ApiWorkoutPlanNextRoute
  '/api/workout/plan/today': typeof ApiWorkoutPlanTodayRoute
  '/api/workout/sessions/$id': typeof ApiWorkoutSessionsIdRouteWithChildren
  '/api/workout/exercise-performances/$id/sets': typeof ApiWorkoutExercisePerformancesIdSetsRoute
  '/api/workout/sessions/$id/complete': typeof ApiWorkoutSessionsIdCompleteRoute
  '/api/workout/sessions/$id/skip': typeof ApiWorkoutSessionsIdSkipRoute
  '/api/workout/sessions/$id/start': typeof ApiWorkoutSessionsIdStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/openclaw': typeof OpenclawRoute
  '/search': typeof SearchRoute
  '/thoughts': typeof ThoughtsRoute
  '/trading': typeof TradingRoute
  '/workout': typeof WorkoutRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/honestfit/mission-summary': typeof ApiHonestfitMissionSummaryRoute
  '/api/mcp/search-brain': typeof ApiMcpSearchBrainRoute
  '/api/openclaw/agents': typeof ApiOpenclawAgentsRouteWithChildren
  '/api/openclaw/health': typeof ApiOpenclawHealthRoute
  '/api/tournament/leaderboard': typeof ApiTournamentLeaderboardRoute
  '/api/tournament/live': typeof ApiTournamentLiveRoute
  '/api/tournament/rounds': typeof ApiTournamentRoundsRoute
  '/api/tournament/start': typeof ApiTournamentStartRoute
  '/api/workout/analytics': typeof ApiWorkoutAnalyticsRoute
  '/api/workout/audit': typeof ApiWorkoutAuditRoute
  '/api/workout/body-metrics': typeof ApiWorkoutBodyMetricsRoute
  '/api/workout/dashboard': typeof ApiWorkoutDashboardRoute
  '/api/workout/exercises': typeof ApiWorkoutExercisesRoute
  '/api/workout/profile': typeof ApiWorkoutProfileRoute
  '/api/workout/sessions': typeof ApiWorkoutSessionsRouteWithChildren
  '/api/ingest/thoughts/activity': typeof ApiIngestThoughtsActivityRoute
  '/api/ingest/thoughts/recent': typeof ApiIngestThoughtsRecentRoute
  '/api/ingest/trading/bracket': typeof ApiIngestTradingBracketRoute
  '/api/openclaw/agents/$id': typeof ApiOpenclawAgentsIdRoute
  '/api/workout/chat/command': typeof ApiWorkoutChatCommandRoute
  '/api/workout/chat/help': typeof ApiWorkoutChatHelpRoute
  '/api/workout/plan/generate': typeof ApiWorkoutPlanGenerateRoute
  '/api/workout/plan/next': typeof ApiWorkoutPlanNextRoute
  '/api/workout/plan/today': typeof ApiWorkoutPlanTodayRoute
  '/api/workout/sessions/$id': typeof ApiWorkoutSessionsIdRouteWithChildren
  '/api/workout/exercise-performances/$id/sets': typeof ApiWorkoutExercisePerformancesIdSetsRoute
  '/api/workout/sessions/$id/complete': typeof ApiWorkoutSessionsIdCompleteRoute
  '/api/workout/sessions/$id/skip': typeof ApiWorkoutSessionsIdSkipRoute
  '/api/workout/sessions/$id/start': typeof ApiWorkoutSessionsIdStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/openclaw': typeof OpenclawRoute
  '/search': typeof SearchRoute
  '/thoughts': typeof ThoughtsRoute
  '/trading': typeof TradingRoute
  '/workout': typeof WorkoutRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/honestfit/mission-summary': typeof ApiHonestfitMissionSummaryRoute
  '/api/mcp/search-brain': typeof ApiMcpSearchBrainRoute
  '/api/openclaw/agents': typeof ApiOpenclawAgentsRouteWithChildren
  '/api/openclaw/health': typeof ApiOpenclawHealthRoute
  '/api/tournament/leaderboard': typeof ApiTournamentLeaderboardRoute
  '/api/tournament/live': typeof ApiTournamentLiveRoute
  '/api/tournament/rounds': typeof ApiTournamentRoundsRoute
  '/api/tournament/start': typeof ApiTournamentStartRoute
  '/api/workout/analytics': typeof ApiWorkoutAnalyticsRoute
  '/api/workout/audit': typeof ApiWorkoutAuditRoute
  '/api/workout/body-metrics': typeof ApiWorkoutBodyMetricsRoute
  '/api/workout/dashboard': typeof ApiWorkoutDashboardRoute
  '/api/workout/exercises': typeof ApiWorkoutExercisesRoute
  '/api/workout/profile': typeof ApiWorkoutProfileRoute
  '/api/workout/sessions': typeof ApiWorkoutSessionsRouteWithChildren
  '/api/ingest/thoughts/activity': typeof ApiIngestThoughtsActivityRoute
  '/api/ingest/thoughts/recent': typeof ApiIngestThoughtsRecentRoute
  '/api/ingest/trading/bracket': typeof ApiIngestTradingBracketRoute
  '/api/openclaw/agents/$id': typeof ApiOpenclawAgentsIdRoute
  '/api/workout/chat/command': typeof ApiWorkoutChatCommandRoute
  '/api/workout/chat/help': typeof ApiWorkoutChatHelpRoute
  '/api/workout/plan/generate': typeof ApiWorkoutPlanGenerateRoute
  '/api/workout/plan/next': typeof ApiWorkoutPlanNextRoute
  '/api/workout/plan/today': typeof ApiWorkoutPlanTodayRoute
  '/api/workout/sessions/$id': typeof ApiWorkoutSessionsIdRouteWithChildren
  '/api/workout/exercise-performances/$id/sets': typeof ApiWorkoutExercisePerformancesIdSetsRoute
  '/api/workout/sessions/$id/complete': typeof ApiWorkoutSessionsIdCompleteRoute
  '/api/workout/sessions/$id/skip': typeof ApiWorkoutSessionsIdSkipRoute
  '/api/workout/sessions/$id/start': typeof ApiWorkoutSessionsIdStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/login'
    | '/logout'
    | '/openclaw'
    | '/search'
    | '/thoughts'
    | '/trading'
    | '/workout'
    | '/agents/$id'
    | '/api/honestfit/mission-summary'
    | '/api/mcp/search-brain'
    | '/api/openclaw/agents'
    | '/api/openclaw/health'
    | '/api/tournament/leaderboard'
    | '/api/tournament/live'
    | '/api/tournament/rounds'
    | '/api/tournament/start'
    | '/api/workout/analytics'
    | '/api/workout/audit'
    | '/api/workout/body-metrics'
    | '/api/workout/dashboard'
    | '/api/workout/exercises'
    | '/api/workout/profile'
    | '/api/workout/sessions'
    | '/api/ingest/thoughts/activity'
    | '/api/ingest/thoughts/recent'
    | '/api/ingest/trading/bracket'
    | '/api/openclaw/agents/$id'
    | '/api/workout/chat/command'
    | '/api/workout/chat/help'
    | '/api/workout/plan/generate'
    | '/api/workout/plan/next'
    | '/api/workout/plan/today'
    | '/api/workout/sessions/$id'
    | '/api/workout/exercise-performances/$id/sets'
    | '/api/workout/sessions/$id/complete'
    | '/api/workout/sessions/$id/skip'
    | '/api/workout/sessions/$id/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/login'
    | '/logout'
    | '/openclaw'
    | '/search'
    | '/thoughts'
    | '/trading'
    | '/workout'
    | '/agents/$id'
    | '/api/honestfit/mission-summary'
    | '/api/mcp/search-brain'
    | '/api/openclaw/agents'
    | '/api/openclaw/health'
    | '/api/tournament/leaderboard'
    | '/api/tournament/live'
    | '/api/tournament/rounds'
    | '/api/tournament/start'
    | '/api/workout/analytics'
    | '/api/workout/audit'
    | '/api/workout/body-metrics'
    | '/api/workout/dashboard'
    | '/api/workout/exercises'
    | '/api/workout/profile'
    | '/api/workout/sessions'
    | '/api/ingest/thoughts/activity'
    | '/api/ingest/thoughts/recent'
    | '/api/ingest/trading/bracket'
    | '/api/openclaw/agents/$id'
    | '/api/workout/chat/command'
    | '/api/workout/chat/help'
    | '/api/workout/plan/generate'
    | '/api/workout/plan/next'
    | '/api/workout/plan/today'
    | '/api/workout/sessions/$id'
    | '/api/workout/exercise-performances/$id/sets'
    | '/api/workout/sessions/$id/complete'
    | '/api/workout/sessions/$id/skip'
    | '/api/workout/sessions/$id/start'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/login'
    | '/logout'
    | '/openclaw'
    | '/search'
    | '/thoughts'
    | '/trading'
    | '/workout'
    | '/agents/$id'
    | '/api/honestfit/mission-summary'
    | '/api/mcp/search-brain'
    | '/api/openclaw/agents'
    | '/api/openclaw/health'
    | '/api/tournament/leaderboard'
    | '/api/tournament/live'
    | '/api/tournament/rounds'
    | '/api/tournament/start'
    | '/api/workout/analytics'
    | '/api/workout/audit'
    | '/api/workout/body-metrics'
    | '/api/workout/dashboard'
    | '/api/workout/exercises'
    | '/api/workout/profile'
    | '/api/workout/sessions'
    | '/api/ingest/thoughts/activity'
    | '/api/ingest/thoughts/recent'
    | '/api/ingest/trading/bracket'
    | '/api/openclaw/agents/$id'
    | '/api/workout/chat/command'
    | '/api/workout/chat/help'
    | '/api/workout/plan/generate'
    | '/api/workout/plan/next'
    | '/api/workout/plan/today'
    | '/api/workout/sessions/$id'
    | '/api/workout/exercise-performances/$id/sets'
    | '/api/workout/sessions/$id/complete'
    | '/api/workout/sessions/$id/skip'
    | '/api/workout/sessions/$id/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OpenclawRoute: typeof OpenclawRoute
  SearchRoute: typeof SearchRoute
  ThoughtsRoute: typeof ThoughtsRoute
  TradingRoute: typeof TradingRoute
  WorkoutRoute: typeof WorkoutRoute
  ApiHonestfitMissionSummaryRoute: typeof ApiHonestfitMissionSummaryRoute
  ApiMcpSearchBrainRoute: typeof ApiMcpSearchBrainRoute
  ApiOpenclawAgentsRoute: typeof ApiOpenclawAgentsRouteWithChildren
  ApiOpenclawHealthRoute: typeof ApiOpenclawHealthRoute
  ApiTournamentLeaderboardRoute: typeof ApiTournamentLeaderboardRoute
  ApiTournamentLiveRoute: typeof ApiTournamentLiveRoute
  ApiTournamentRoundsRoute: typeof ApiTournamentRoundsRoute
  ApiTournamentStartRoute: typeof ApiTournamentStartRoute
  ApiWorkoutAnalyticsRoute: typeof ApiWorkoutAnalyticsRoute
  ApiWorkoutAuditRoute: typeof ApiWorkoutAuditRoute
  ApiWorkoutBodyMetricsRoute: typeof ApiWorkoutBodyMetricsRoute
  ApiWorkoutDashboardRoute: typeof ApiWorkoutDashboardRoute
  ApiWorkoutExercisesRoute: typeof ApiWorkoutExercisesRoute
  ApiWorkoutProfileRoute: typeof ApiWorkoutProfileRoute
  ApiWorkoutSessionsRoute: typeof ApiWorkoutSessionsRouteWithChildren
  ApiIngestThoughtsActivityRoute: typeof ApiIngestThoughtsActivityRoute
  ApiIngestThoughtsRecentRoute: typeof ApiIngestThoughtsRecentRoute
  ApiIngestTradingBracketRoute: typeof ApiIngestTradingBracketRoute
  ApiWorkoutChatCommandRoute: typeof ApiWorkoutChatCommandRoute
  ApiWorkoutChatHelpRoute: typeof ApiWorkoutChatHelpRoute
  ApiWorkoutPlanGenerateRoute: typeof ApiWorkoutPlanGenerateRoute
  ApiWorkoutPlanNextRoute: typeof ApiWorkoutPlanNextRoute
  ApiWorkoutPlanTodayRoute: typeof ApiWorkoutPlanTodayRoute
  ApiWorkoutExercisePerformancesIdSetsRoute: typeof ApiWorkoutExercisePerformancesIdSetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openclaw': {
      id: '/openclaw'
      path: '/openclaw'
      fullPath: '/openclaw'
      preLoaderRoute: typeof OpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/api/workout/sessions': {
      id: '/api/workout/sessions'
      path: '/api/workout/sessions'
      fullPath: '/api/workout/sessions'
      preLoaderRoute: typeof ApiWorkoutSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/profile': {
      id: '/api/workout/profile'
      path: '/api/workout/profile'
      fullPath: '/api/workout/profile'
      preLoaderRoute: typeof ApiWorkoutProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/exercises': {
      id: '/api/workout/exercises'
      path: '/api/workout/exercises'
      fullPath: '/api/workout/exercises'
      preLoaderRoute: typeof ApiWorkoutExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/dashboard': {
      id: '/api/workout/dashboard'
      path: '/api/workout/dashboard'
      fullPath: '/api/workout/dashboard'
      preLoaderRoute: typeof ApiWorkoutDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/body-metrics': {
      id: '/api/workout/body-metrics'
      path: '/api/workout/body-metrics'
      fullPath: '/api/workout/body-metrics'
      preLoaderRoute: typeof ApiWorkoutBodyMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/audit': {
      id: '/api/workout/audit'
      path: '/api/workout/audit'
      fullPath: '/api/workout/audit'
      preLoaderRoute: typeof ApiWorkoutAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/analytics': {
      id: '/api/workout/analytics'
      path: '/api/workout/analytics'
      fullPath: '/api/workout/analytics'
      preLoaderRoute: typeof ApiWorkoutAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/start': {
      id: '/api/tournament/start'
      path: '/api/tournament/start'
      fullPath: '/api/tournament/start'
      preLoaderRoute: typeof ApiTournamentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/rounds': {
      id: '/api/tournament/rounds'
      path: '/api/tournament/rounds'
      fullPath: '/api/tournament/rounds'
      preLoaderRoute: typeof ApiTournamentRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/live': {
      id: '/api/tournament/live'
      path: '/api/tournament/live'
      fullPath: '/api/tournament/live'
      preLoaderRoute: typeof ApiTournamentLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/leaderboard': {
      id: '/api/tournament/leaderboard'
      path: '/api/tournament/leaderboard'
      fullPath: '/api/tournament/leaderboard'
      preLoaderRoute: typeof ApiTournamentLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openclaw/health': {
      id: '/api/openclaw/health'
      path: '/api/openclaw/health'
      fullPath: '/api/openclaw/health'
      preLoaderRoute: typeof ApiOpenclawHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openclaw/agents': {
      id: '/api/openclaw/agents'
      path: '/api/openclaw/agents'
      fullPath: '/api/openclaw/agents'
      preLoaderRoute: typeof ApiOpenclawAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/search-brain': {
      id: '/api/mcp/search-brain'
      path: '/api/mcp/search-brain'
      fullPath: '/api/mcp/search-brain'
      preLoaderRoute: typeof ApiMcpSearchBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/honestfit/mission-summary': {
      id: '/api/honestfit/mission-summary'
      path: '/api/honestfit/mission-summary'
      fullPath: '/api/honestfit/mission-summary'
      preLoaderRoute: typeof ApiHonestfitMissionSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/sessions/$id': {
      id: '/api/workout/sessions/$id'
      path: '/$id'
      fullPath: '/api/workout/sessions/$id'
      preLoaderRoute: typeof ApiWorkoutSessionsIdRouteImport
      parentRoute: typeof ApiWorkoutSessionsRoute
    }
    '/api/workout/plan/today': {
      id: '/api/workout/plan/today'
      path: '/api/workout/plan/today'
      fullPath: '/api/workout/plan/today'
      preLoaderRoute: typeof ApiWorkoutPlanTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/plan/next': {
      id: '/api/workout/plan/next'
      path: '/api/workout/plan/next'
      fullPath: '/api/workout/plan/next'
      preLoaderRoute: typeof ApiWorkoutPlanNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/plan/generate': {
      id: '/api/workout/plan/generate'
      path: '/api/workout/plan/generate'
      fullPath: '/api/workout/plan/generate'
      preLoaderRoute: typeof ApiWorkoutPlanGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/chat/help': {
      id: '/api/workout/chat/help'
      path: '/api/workout/chat/help'
      fullPath: '/api/workout/chat/help'
      preLoaderRoute: typeof ApiWorkoutChatHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/chat/command': {
      id: '/api/workout/chat/command'
      path: '/api/workout/chat/command'
      fullPath: '/api/workout/chat/command'
      preLoaderRoute: typeof ApiWorkoutChatCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openclaw/agents/$id': {
      id: '/api/openclaw/agents/$id'
      path: '/$id'
      fullPath: '/api/openclaw/agents/$id'
      preLoaderRoute: typeof ApiOpenclawAgentsIdRouteImport
      parentRoute: typeof ApiOpenclawAgentsRoute
    }
    '/api/ingest/trading/bracket': {
      id: '/api/ingest/trading/bracket'
      path: '/api/ingest/trading/bracket'
      fullPath: '/api/ingest/trading/bracket'
      preLoaderRoute: typeof ApiIngestTradingBracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/thoughts/recent': {
      id: '/api/ingest/thoughts/recent'
      path: '/api/ingest/thoughts/recent'
      fullPath: '/api/ingest/thoughts/recent'
      preLoaderRoute: typeof ApiIngestThoughtsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/thoughts/activity': {
      id: '/api/ingest/thoughts/activity'
      path: '/api/ingest/thoughts/activity'
      fullPath: '/api/ingest/thoughts/activity'
      preLoaderRoute: typeof ApiIngestThoughtsActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workout/sessions/$id/start': {
      id: '/api/workout/sessions/$id/start'
      path: '/start'
      fullPath: '/api/workout/sessions/$id/start'
      preLoaderRoute: typeof ApiWorkoutSessionsIdStartRouteImport
      parentRoute: typeof ApiWorkoutSessionsIdRoute
    }
    '/api/workout/sessions/$id/skip': {
      id: '/api/workout/sessions/$id/skip'
      path: '/skip'
      fullPath: '/api/workout/sessions/$id/skip'
      preLoaderRoute: typeof ApiWorkoutSessionsIdSkipRouteImport
      parentRoute: typeof ApiWorkoutSessionsIdRoute
    }
    '/api/workout/sessions/$id/complete': {
      id: '/api/workout/sessions/$id/complete'
      path: '/complete'
      fullPath: '/api/workout/sessions/$id/complete'
      preLoaderRoute: typeof ApiWorkoutSessionsIdCompleteRouteImport
      parentRoute: typeof ApiWorkoutSessionsIdRoute
    }
    '/api/workout/exercise-performances/$id/sets': {
      id: '/api/workout/exercise-performances/$id/sets'
      path: '/api/workout/exercise-performances/$id/sets'
      fullPath: '/api/workout/exercise-performances/$id/sets'
      preLoaderRoute: typeof ApiWorkoutExercisePerformancesIdSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ApiOpenclawAgentsRouteChildren {
  ApiOpenclawAgentsIdRoute: typeof ApiOpenclawAgentsIdRoute
}

const ApiOpenclawAgentsRouteChildren: ApiOpenclawAgentsRouteChildren = {
  ApiOpenclawAgentsIdRoute: ApiOpenclawAgentsIdRoute,
}

const ApiOpenclawAgentsRouteWithChildren =
  ApiOpenclawAgentsRoute._addFileChildren(ApiOpenclawAgentsRouteChildren)

interface ApiWorkoutSessionsIdRouteChildren {
  ApiWorkoutSessionsIdCompleteRoute: typeof ApiWorkoutSessionsIdCompleteRoute
  ApiWorkoutSessionsIdSkipRoute: typeof ApiWorkoutSessionsIdSkipRoute
  ApiWorkoutSessionsIdStartRoute: typeof ApiWorkoutSessionsIdStartRoute
}

const ApiWorkoutSessionsIdRouteChildren: ApiWorkoutSessionsIdRouteChildren = {
  ApiWorkoutSessionsIdCompleteRoute: ApiWorkoutSessionsIdCompleteRoute,
  ApiWorkoutSessionsIdSkipRoute: ApiWorkoutSessionsIdSkipRoute,
  ApiWorkoutSessionsIdStartRoute: ApiWorkoutSessionsIdStartRoute,
}

const ApiWorkoutSessionsIdRouteWithChildren =
  ApiWorkoutSessionsIdRoute._addFileChildren(ApiWorkoutSessionsIdRouteChildren)

interface ApiWorkoutSessionsRouteChildren {
  ApiWorkoutSessionsIdRoute: typeof ApiWorkoutSessionsIdRouteWithChildren
}

const ApiWorkoutSessionsRouteChildren: ApiWorkoutSessionsRouteChildren = {
  ApiWorkoutSessionsIdRoute: ApiWorkoutSessionsIdRouteWithChildren,
}

const ApiWorkoutSessionsRouteWithChildren =
  ApiWorkoutSessionsRoute._addFileChildren(ApiWorkoutSessionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OpenclawRoute: OpenclawRoute,
  SearchRoute: SearchRoute,
  ThoughtsRoute: ThoughtsRoute,
  TradingRoute: TradingRoute,
  WorkoutRoute: WorkoutRoute,
  ApiHonestfitMissionSummaryRoute: ApiHonestfitMissionSummaryRoute,
  ApiMcpSearchBrainRoute: ApiMcpSearchBrainRoute,
  ApiOpenclawAgentsRoute: ApiOpenclawAgentsRouteWithChildren,
  ApiOpenclawHealthRoute: ApiOpenclawHealthRoute,
  ApiTournamentLeaderboardRoute: ApiTournamentLeaderboardRoute,
  ApiTournamentLiveRoute: ApiTournamentLiveRoute,
  ApiTournamentRoundsRoute: ApiTournamentRoundsRoute,
  ApiTournamentStartRoute: ApiTournamentStartRoute,
  ApiWorkoutAnalyticsRoute: ApiWorkoutAnalyticsRoute,
  ApiWorkoutAuditRoute: ApiWorkoutAuditRoute,
  ApiWorkoutBodyMetricsRoute: ApiWorkoutBodyMetricsRoute,
  ApiWorkoutDashboardRoute: ApiWorkoutDashboardRoute,
  ApiWorkoutExercisesRoute: ApiWorkoutExercisesRoute,
  ApiWorkoutProfileRoute: ApiWorkoutProfileRoute,
  ApiWorkoutSessionsRoute: ApiWorkoutSessionsRouteWithChildren,
  ApiIngestThoughtsActivityRoute: ApiIngestThoughtsActivityRoute,
  ApiIngestThoughtsRecentRoute: ApiIngestThoughtsRecentRoute,
  ApiIngestTradingBracketRoute: ApiIngestTradingBracketRoute,
  ApiWorkoutChatCommandRoute: ApiWorkoutChatCommandRoute,
  ApiWorkoutChatHelpRoute: ApiWorkoutChatHelpRoute,
  ApiWorkoutPlanGenerateRoute: ApiWorkoutPlanGenerateRoute,
  ApiWorkoutPlanNextRoute: ApiWorkoutPlanNextRoute,
  ApiWorkoutPlanTodayRoute: ApiWorkoutPlanTodayRoute,
  ApiWorkoutExercisePerformancesIdSetsRoute:
    ApiWorkoutExercisePerformancesIdSetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
