/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as ThoughtsRouteImport } from './routes/thoughts'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OpenclawRouteImport } from './routes/openclaw'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ApiTournamentStartRouteImport } from './routes/api/tournament/start'
import { Route as ApiTournamentRoundsRouteImport } from './routes/api/tournament/rounds'
import { Route as ApiTournamentLiveRouteImport } from './routes/api/tournament/live'
import { Route as ApiTournamentLeaderboardRouteImport } from './routes/api/tournament/leaderboard'
import { Route as ApiOpenclawHealthRouteImport } from './routes/api/openclaw/health'
import { Route as ApiOpenclawAgentsRouteImport } from './routes/api/openclaw/agents'
import { Route as ApiMcpSearchBrainRouteImport } from './routes/api/mcp/search-brain'
import { Route as ApiOpenclawAgentsIdRouteImport } from './routes/api/openclaw/agents.$id'
import { Route as ApiIngestTradingBracketRouteImport } from './routes/api/ingest/trading.bracket'
import { Route as ApiIngestThoughtsRecentRouteImport } from './routes/api/ingest/thoughts.recent'
import { Route as ApiIngestThoughtsActivityRouteImport } from './routes/api/ingest/thoughts.activity'

const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRoute = ThoughtsRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenclawRoute = OpenclawRouteImport.update({
  id: '/openclaw',
  path: '/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const ApiTournamentStartRoute = ApiTournamentStartRouteImport.update({
  id: '/api/tournament/start',
  path: '/api/tournament/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentRoundsRoute = ApiTournamentRoundsRouteImport.update({
  id: '/api/tournament/rounds',
  path: '/api/tournament/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentLiveRoute = ApiTournamentLiveRouteImport.update({
  id: '/api/tournament/live',
  path: '/api/tournament/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTournamentLeaderboardRoute =
  ApiTournamentLeaderboardRouteImport.update({
    id: '/api/tournament/leaderboard',
    path: '/api/tournament/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOpenclawHealthRoute = ApiOpenclawHealthRouteImport.update({
  id: '/api/openclaw/health',
  path: '/api/openclaw/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenclawAgentsRoute = ApiOpenclawAgentsRouteImport.update({
  id: '/api/openclaw/agents',
  path: '/api/openclaw/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpSearchBrainRoute = ApiMcpSearchBrainRouteImport.update({
  id: '/api/mcp/search-brain',
  path: '/api/mcp/search-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenclawAgentsIdRoute = ApiOpenclawAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOpenclawAgentsRoute,
} as any)
const ApiIngestTradingBracketRoute = ApiIngestTradingBracketRouteImport.update({
  id: '/api/ingest/trading/bracket',
  path: '/api/ingest/trading/bracket',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestThoughtsRecentRoute = ApiIngestThoughtsRecentRouteImport.update({
  id: '/api/ingest/thoughts/recent',
  path: '/api/ingest/thoughts/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestThoughtsActivityRoute =
  ApiIngestThoughtsActivityRouteImport.update({
    id: '/api/ingest/thoughts/activity',
    path: '/api/ingest/thoughts/activity',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/openclaw': typeof OpenclawRoute
  '/search': typeof SearchRoute
  '/thoughts': typeof ThoughtsRoute
  '/trading': typeof TradingRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/mcp/search-brain': typeof ApiMcpSearchBrainRoute
  '/api/openclaw/agents': typeof ApiOpenclawAgentsRouteWithChildren
  '/api/openclaw/health': typeof ApiOpenclawHealthRoute
  '/api/tournament/leaderboard': typeof ApiTournamentLeaderboardRoute
  '/api/tournament/live': typeof ApiTournamentLiveRoute
  '/api/tournament/rounds': typeof ApiTournamentRoundsRoute
  '/api/tournament/start': typeof ApiTournamentStartRoute
  '/api/ingest/thoughts/activity': typeof ApiIngestThoughtsActivityRoute
  '/api/ingest/thoughts/recent': typeof ApiIngestThoughtsRecentRoute
  '/api/ingest/trading/bracket': typeof ApiIngestTradingBracketRoute
  '/api/openclaw/agents/$id': typeof ApiOpenclawAgentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/openclaw': typeof OpenclawRoute
  '/search': typeof SearchRoute
  '/thoughts': typeof ThoughtsRoute
  '/trading': typeof TradingRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/mcp/search-brain': typeof ApiMcpSearchBrainRoute
  '/api/openclaw/agents': typeof ApiOpenclawAgentsRouteWithChildren
  '/api/openclaw/health': typeof ApiOpenclawHealthRoute
  '/api/tournament/leaderboard': typeof ApiTournamentLeaderboardRoute
  '/api/tournament/live': typeof ApiTournamentLiveRoute
  '/api/tournament/rounds': typeof ApiTournamentRoundsRoute
  '/api/tournament/start': typeof ApiTournamentStartRoute
  '/api/ingest/thoughts/activity': typeof ApiIngestThoughtsActivityRoute
  '/api/ingest/thoughts/recent': typeof ApiIngestThoughtsRecentRoute
  '/api/ingest/trading/bracket': typeof ApiIngestTradingBracketRoute
  '/api/openclaw/agents/$id': typeof ApiOpenclawAgentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/openclaw': typeof OpenclawRoute
  '/search': typeof SearchRoute
  '/thoughts': typeof ThoughtsRoute
  '/trading': typeof TradingRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/mcp/search-brain': typeof ApiMcpSearchBrainRoute
  '/api/openclaw/agents': typeof ApiOpenclawAgentsRouteWithChildren
  '/api/openclaw/health': typeof ApiOpenclawHealthRoute
  '/api/tournament/leaderboard': typeof ApiTournamentLeaderboardRoute
  '/api/tournament/live': typeof ApiTournamentLiveRoute
  '/api/tournament/rounds': typeof ApiTournamentRoundsRoute
  '/api/tournament/start': typeof ApiTournamentStartRoute
  '/api/ingest/thoughts/activity': typeof ApiIngestThoughtsActivityRoute
  '/api/ingest/thoughts/recent': typeof ApiIngestThoughtsRecentRoute
  '/api/ingest/trading/bracket': typeof ApiIngestTradingBracketRoute
  '/api/openclaw/agents/$id': typeof ApiOpenclawAgentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/login'
    | '/logout'
    | '/openclaw'
    | '/search'
    | '/thoughts'
    | '/trading'
    | '/agents/$id'
    | '/api/mcp/search-brain'
    | '/api/openclaw/agents'
    | '/api/openclaw/health'
    | '/api/tournament/leaderboard'
    | '/api/tournament/live'
    | '/api/tournament/rounds'
    | '/api/tournament/start'
    | '/api/ingest/thoughts/activity'
    | '/api/ingest/thoughts/recent'
    | '/api/ingest/trading/bracket'
    | '/api/openclaw/agents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/login'
    | '/logout'
    | '/openclaw'
    | '/search'
    | '/thoughts'
    | '/trading'
    | '/agents/$id'
    | '/api/mcp/search-brain'
    | '/api/openclaw/agents'
    | '/api/openclaw/health'
    | '/api/tournament/leaderboard'
    | '/api/tournament/live'
    | '/api/tournament/rounds'
    | '/api/tournament/start'
    | '/api/ingest/thoughts/activity'
    | '/api/ingest/thoughts/recent'
    | '/api/ingest/trading/bracket'
    | '/api/openclaw/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/login'
    | '/logout'
    | '/openclaw'
    | '/search'
    | '/thoughts'
    | '/trading'
    | '/agents/$id'
    | '/api/mcp/search-brain'
    | '/api/openclaw/agents'
    | '/api/openclaw/health'
    | '/api/tournament/leaderboard'
    | '/api/tournament/live'
    | '/api/tournament/rounds'
    | '/api/tournament/start'
    | '/api/ingest/thoughts/activity'
    | '/api/ingest/thoughts/recent'
    | '/api/ingest/trading/bracket'
    | '/api/openclaw/agents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OpenclawRoute: typeof OpenclawRoute
  SearchRoute: typeof SearchRoute
  ThoughtsRoute: typeof ThoughtsRoute
  TradingRoute: typeof TradingRoute
  ApiMcpSearchBrainRoute: typeof ApiMcpSearchBrainRoute
  ApiOpenclawAgentsRoute: typeof ApiOpenclawAgentsRouteWithChildren
  ApiOpenclawHealthRoute: typeof ApiOpenclawHealthRoute
  ApiTournamentLeaderboardRoute: typeof ApiTournamentLeaderboardRoute
  ApiTournamentLiveRoute: typeof ApiTournamentLiveRoute
  ApiTournamentRoundsRoute: typeof ApiTournamentRoundsRoute
  ApiTournamentStartRoute: typeof ApiTournamentStartRoute
  ApiIngestThoughtsActivityRoute: typeof ApiIngestThoughtsActivityRoute
  ApiIngestThoughtsRecentRoute: typeof ApiIngestThoughtsRecentRoute
  ApiIngestTradingBracketRoute: typeof ApiIngestTradingBracketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openclaw': {
      id: '/openclaw'
      path: '/openclaw'
      fullPath: '/openclaw'
      preLoaderRoute: typeof OpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/api/tournament/start': {
      id: '/api/tournament/start'
      path: '/api/tournament/start'
      fullPath: '/api/tournament/start'
      preLoaderRoute: typeof ApiTournamentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/rounds': {
      id: '/api/tournament/rounds'
      path: '/api/tournament/rounds'
      fullPath: '/api/tournament/rounds'
      preLoaderRoute: typeof ApiTournamentRoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/live': {
      id: '/api/tournament/live'
      path: '/api/tournament/live'
      fullPath: '/api/tournament/live'
      preLoaderRoute: typeof ApiTournamentLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tournament/leaderboard': {
      id: '/api/tournament/leaderboard'
      path: '/api/tournament/leaderboard'
      fullPath: '/api/tournament/leaderboard'
      preLoaderRoute: typeof ApiTournamentLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openclaw/health': {
      id: '/api/openclaw/health'
      path: '/api/openclaw/health'
      fullPath: '/api/openclaw/health'
      preLoaderRoute: typeof ApiOpenclawHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openclaw/agents': {
      id: '/api/openclaw/agents'
      path: '/api/openclaw/agents'
      fullPath: '/api/openclaw/agents'
      preLoaderRoute: typeof ApiOpenclawAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/search-brain': {
      id: '/api/mcp/search-brain'
      path: '/api/mcp/search-brain'
      fullPath: '/api/mcp/search-brain'
      preLoaderRoute: typeof ApiMcpSearchBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openclaw/agents/$id': {
      id: '/api/openclaw/agents/$id'
      path: '/$id'
      fullPath: '/api/openclaw/agents/$id'
      preLoaderRoute: typeof ApiOpenclawAgentsIdRouteImport
      parentRoute: typeof ApiOpenclawAgentsRoute
    }
    '/api/ingest/trading/bracket': {
      id: '/api/ingest/trading/bracket'
      path: '/api/ingest/trading/bracket'
      fullPath: '/api/ingest/trading/bracket'
      preLoaderRoute: typeof ApiIngestTradingBracketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/thoughts/recent': {
      id: '/api/ingest/thoughts/recent'
      path: '/api/ingest/thoughts/recent'
      fullPath: '/api/ingest/thoughts/recent'
      preLoaderRoute: typeof ApiIngestThoughtsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/thoughts/activity': {
      id: '/api/ingest/thoughts/activity'
      path: '/api/ingest/thoughts/activity'
      fullPath: '/api/ingest/thoughts/activity'
      preLoaderRoute: typeof ApiIngestThoughtsActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ApiOpenclawAgentsRouteChildren {
  ApiOpenclawAgentsIdRoute: typeof ApiOpenclawAgentsIdRoute
}

const ApiOpenclawAgentsRouteChildren: ApiOpenclawAgentsRouteChildren = {
  ApiOpenclawAgentsIdRoute: ApiOpenclawAgentsIdRoute,
}

const ApiOpenclawAgentsRouteWithChildren =
  ApiOpenclawAgentsRoute._addFileChildren(ApiOpenclawAgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OpenclawRoute: OpenclawRoute,
  SearchRoute: SearchRoute,
  ThoughtsRoute: ThoughtsRoute,
  TradingRoute: TradingRoute,
  ApiMcpSearchBrainRoute: ApiMcpSearchBrainRoute,
  ApiOpenclawAgentsRoute: ApiOpenclawAgentsRouteWithChildren,
  ApiOpenclawHealthRoute: ApiOpenclawHealthRoute,
  ApiTournamentLeaderboardRoute: ApiTournamentLeaderboardRoute,
  ApiTournamentLiveRoute: ApiTournamentLiveRoute,
  ApiTournamentRoundsRoute: ApiTournamentRoundsRoute,
  ApiTournamentStartRoute: ApiTournamentStartRoute,
  ApiIngestThoughtsActivityRoute: ApiIngestThoughtsActivityRoute,
  ApiIngestThoughtsRecentRoute: ApiIngestThoughtsRecentRoute,
  ApiIngestTradingBracketRoute: ApiIngestTradingBracketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
