/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as HonestFitRouteImport } from './routes/honest-fit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdventuresRouteImport } from './routes/adventures'
import { Route as IndexRouteImport } from './routes/index'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const HonestFitRoute = HonestFitRouteImport.update({
  id: '/honest-fit',
  path: '/honest-fit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresRoute = AdventuresRouteImport.update({
  id: '/adventures',
  path: '/adventures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventures': typeof AdventuresRoute
  '/contact': typeof ContactRoute
  '/honest-fit': typeof HonestFitRoute
  '/resume': typeof ResumeRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventures': typeof AdventuresRoute
  '/contact': typeof ContactRoute
  '/honest-fit': typeof HonestFitRoute
  '/resume': typeof ResumeRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventures': typeof AdventuresRoute
  '/contact': typeof ContactRoute
  '/honest-fit': typeof HonestFitRoute
  '/resume': typeof ResumeRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventures'
    | '/contact'
    | '/honest-fit'
    | '/resume'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adventures' | '/contact' | '/honest-fit' | '/resume' | '/work'
  id:
    | '__root__'
    | '/'
    | '/adventures'
    | '/contact'
    | '/honest-fit'
    | '/resume'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventuresRoute: typeof AdventuresRoute
  ContactRoute: typeof ContactRoute
  HonestFitRoute: typeof HonestFitRoute
  ResumeRoute: typeof ResumeRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honest-fit': {
      id: '/honest-fit'
      path: '/honest-fit'
      fullPath: '/honest-fit'
      preLoaderRoute: typeof HonestFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures': {
      id: '/adventures'
      path: '/adventures'
      fullPath: '/adventures'
      preLoaderRoute: typeof AdventuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventuresRoute: AdventuresRoute,
  ContactRoute: ContactRoute,
  HonestFitRoute: HonestFitRoute,
  ResumeRoute: ResumeRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
